OpenConext/Stepup-tiqr

.travis.yml, ansible/templates/nginx-vhost.conf.j2, app/config/config_test.yml, behat.yml, composer.json, composer.lock, src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Controller/CancelController.php, src/AppBundle/Controller/RegistrationController.php, src/AppBundle/Controller/TiqrAppApiController.php, src/AppBundle/Controller/TqirAppApiController.php, src/AppBundle/Features/Context/ErrorReportContext.php, src/AppBundle/Features/Context/FileLogger.php, src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Features/Context/WebContext.php, src/AppBundle/Features/authentication.feature, src/AppBundle/Features/metadata.feature, src/AppBundle/Features/registration.feature, src/AppBundle/Features/tiqrAuthentication.feature, src/AppBundle/Features/tiqrRegistration.feature, src/AppBundle/Resources/config/services.yml, src/AppBundle/Resources/views/default/authentication.html.twig, src/AppBundle/Tiqr/Legacy/TiqrService.php, src/AppBundle/Tiqr/TiqrServiceInterface.php, src/DevTiqrClientBundle/Controller/QrLinkController.php, src/SpBundle/Controller/SPController.php, web/app_test.php
Add login for authentication and registration flows.
I have added comments to explain some changes.
- Add test env, with overridden logger.
- Fixed composer.json phpmd, dit not work.
=> Add authentication and registration logging

src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Tiqr/Legacy/TiqrService.php, src/AppBundle/Tiqr/Legacy/TiqrUser.php, src/AppBundle/Tiqr/TiqrServiceInterface.php, src/AppBundle/Tiqr/TiqrUserInterface.php
(cherry picked from commit 8a2c9b2)
=> Add push notification to the authentication process

app/Resources/SurfnetGsspBundle/views/StepupGssp/ssoReturn.html.twig, app/Resources/scss/application.scss, app/Resources/views/base.html.twig, src/AppBundle/Resources/views/default/authentication.html.twig, src/AppBundle/Resources/views/default/registration.html.twig
Fixes applied, among others:
- broken markup / footer too big
- missing horizontal line above footer
- no page title on error pages
=> Improve styling to be more in line with gateway

app/Resources/scss/application.scss, app/Resources/scss/vars.scss, src/AppBundle/Features/authentication.feature, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml, src/AppBundle/Resources/views/default/authentication.html.twig, web/images/spinner.svg
Updated the authentication styling to match the design
Amongst the changed:
- Added the spinner
- By default, do not show the QR code
- When the QR code is opened, the spinner is hidden
=> Improve registration styling

app/Resources/views/base.html.twig, src/AppBundle/Controller/InfoController.php, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml, src/AppBundle/Resources/views/default/info.html.twig
A simple information page is added. The app links to this page when
the user requests information about tiqr.
=> Provide the /info.html endpoint

app/config/parameters.yml.dist, src/AppBundle/Tiqr/Legacy/TiqrService.php, src/AppBundle/Tiqr/TiqrFactory.php
This account name is based on the name already present in the tiqr
service config. Documentation was added to the Stepup-Deploy tiqr parameter.yml Ninja template.
=> Set configured account name during enrollment

src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml
Different terms where used for push notifications in Dutch and English.
These have been synced to: Push notificatie in Dutch and push
notification in English.
See: https://www.pivotaltracker.com/n/projects/1163646/stories/156334113/comments/189109848 for details.
=> Synchronize push notification naming convention

app/Resources/scss/application.scss
There are two changes included in this PR:
* hide mouse cursor when hovering the image
* never scale the image, always use the actual image size
=> Improve QR code display

app/Resources/SurfnetGsspBundle/views/StepupGssp/ssoReturn.html.twig, app/Resources/scss/application.scss, app/Resources/views/base.html.twig, src/AppBundle/Resources/views/default/authentication.html.twig, src/AppBundle/Resources/views/default/registration.html.twig
Changes:
* horizontal line above footer was not wide enough
* text alignment on authentication page was off
=> Styling improvements

.travis.yml, README.md, composer.json, composer.lock
Resolves the following security issues:
* CVE-2018-11407: CVE-2018-11407: Unauthorized access on a misconfigured LDAP server when using an empty password
https://symfony.com/cve-2018-11407
* CVE-2018-11386: CVE-2018-11386: Denial of service when using PDOSessionHandler
https://symfony.com/cve-2018-11386
* CVE-2018-11406: CVE-2018-11406: CSRF Token Fixation
https://symfony.com/cve-2018-11406
* CVE-2018-11408: CVE-2018-11408: Open redirect vulnerability on security handlers
https://symfony.com/cve-2018-11408
* CVE-2018-11385: CVE-2018-11385: Session Fixation Issue for Guard Authentication
https://symfony.com/cve-2018-11385
=> Update symfony to 3.4.11

src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Features/tiqrRegistration.feature
=> Fix typo in behat scenario

src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml
Fix grammar and update messages to be more in line with the rest of Stepup
=> Update tiqr messages

docs/personal-data.md
To be referenced from https://github.com/OpenConext/Stepup-Deploy/wiki/Personal-Data
=> Describe personal data stored by Stepup-tiqr

.travis.yml, CHANGELOG.md, src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Resources/views/default/authentication.html.twig
https://www.pivotaltracker.com/story/show/161311010
=> Add authenticateUrl to authentication page

src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml
Open links in blank window as not to interrupt registration flow.
=> Make link to app store use https for enhanced trust.

composer.lock
For more information see:
https://symfony.com/blog/twig-sandbox-information-disclosure
=> Update Twig, harden against security vulnerability

composer.lock
Fixes:
[CVE-2019-10912]: https://symfony.com/cve-2019-10912
[CVE-2019-10909]: https://symfony.com/cve-2019-10909
[CVE-2019-10910]: https://symfony.com/cve-2019-10910
[CVE-2019-10911]: https://symfony.com/cve-2019-10911
[CVE-2019-10912]: https://symfony.com/cve-2019-10912
[CVE-2019-10913]: https://symfony.com/cve-2019-10913
=> Update symfony/symfony and symfony/phpunit-bridge

.gitignore, .travis.yml, config/legacy/parameters.yaml.dist, config/services.yaml
To keep the layout/setup the same across stepup projects
the parameter file is moved to the legacy folder.
=> Move parameters to legacy folder

CHANGELOG.md, public/typescript/AuthenticationPageService.ts, webpack.config.js
Switch to location.reload after successful login
=> Use windows.location instead of location

.travis.yml, CHANGELOG.md, composer.json, composer.lock, src/AppBundle/Resources/javascript/AuthenticationPageService.ts, src/DevTiqrClientBundle/Command/AuthenticationCommand.php, src/DevTiqrClientBundle/Command/RegistrationCommand.php, yarn.lock
This will backport the updates in #106 to the Tiqr version using php5.6 and SF3
=> Backport location reload

src/Controller/RegistrationController.php, src/Features/Context/TiqrContext.php
=> Add tiqrenroll protocol to enrollment URL

.github/workflows/tag-release.yml, composer.json, homestead/Homestead.yaml
This workflow will start a release procedure using Stepup-Build scripts. Resulting in a tarbal and shasum that is uploaded to the github release page
=> Add tag release Github Actions workflow

src/Controller/TiqrAppApiController.php, src/Features/authentication.feature, src/Features/registration.feature
Log the version information that a tiqr client sends during authentication and enrollement:
- The HTTP User-Agent header
- The version parameter in the HTTP form POST
=> Log tiqr client version information

src/Controller/TiqrAppApiController.php, src/Features/authentication.feature, src/Features/registration.feature
This feature was lost when creating 3.4.0
=> Reinstate logging of tiqr client version information introduced in 3.1.4

docker/Dockerfile.prod, docker/Dockerfile.test, docker/conf/zz-docker.ini
TIQR needs allow_url_fopen to be enabled
=> Docker: Add php.ini override file.

.github/workflows/build-push-docker-image.yml, docker/Dockerfile.prod
This brings the image in line with the other images, setting default labels and adding version information for the info endpoint to consume
=> Docker: Add labels and env variables

composer.json, composer.lock, config/routes.yaml, src/HealthCheck/HealthCheckResultDto.php, src/HealthCheck/StateStorageHealthCheck.php, src/HealthCheck/UserSecretStorageHealthCheck.php, src/HealthCheck/UserStorageHealthCheck.php, src/Tiqr/Legacy/TiqrService.php, src/Tiqr/Legacy/TiqrUserRepository.php, src/Tiqr/TiqrServiceInterface.php, src/Tiqr/TiqrUserRepositoryInterface.php, tests/Unit/StateStorageHealthCheckTest.php, tests/Unit/UserSecretStorageHealthCheckTest.php, tests/Unit/UserStorageHealthCheckTest.php
Implements the healthchecks from the tiqr-php-lib into the monitorbundle chain of checks
=> Proxy the health checks from tiqr-server-libphp to the Monitor bundle

composer.lock
Use the correct version of monitor-bundle
=> Use monitor-bundle 4.3.1

composer.lock
Make new push notification features available. See https://github.com/Tiqr/tiqr-server-libphp/pull/55
=> Update tiqr-server-libphp to 4.3.1

config/services.yaml, src/Controller/AuthenticationController.php, src/Controller/AuthenticationNotificationController.php, src/Controller/AuthenticationQrController.php, src/Controller/AuthenticationStatusController.php
Some additional bootstrapping was required to allow for this (in services.yaml).
=> 2. Move Authn Status to own controller
