composer.json
- add `archive.exclude` to _include_ assets generated with `composer install` and `composer encore`.
- remove `"symfony-assets-install": "relative"` as this will create symlinks which seem to be ignored when creating tar balls with `composer archive`.
=> make composer generate archives containing assets

app/config/config.yml, src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Controller/RegistrationController.php, src/AppBundle/Controller/TiqrAppApiController.php, src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Resources/config/services.yml, src/AppBundle/Tiqr/Legacy/TiqrService.php, src/AppBundle/Tiqr/TiqrFactory.php, src/AppBundle/Tiqr/TiqrServiceInterface.php, src/DevTiqrClientBundle/Controller/QrLinkController.php
The sari used in log messages for requests from the app are now the
same as the one used in the corresponding web requests. This is
achieved by maintaining a mapping between the session
identifier (the tiqr enrollment key or tiqr session key) and the sari
request id.
=> Log the same sari request ID in web and app requests

app/config/parameters.yml.dist
An example Android gcm and Apple apns configuration was added to the
library setting of the `tiqr_library_options`.
=> Add pushnotification config to parameters.yml.dist

src/AppBundle/EventSubscriber/LocaleResponseListener.php
The locale of tiqr was set in a cookie on a wrong domain (example.com
instead of stepup.example.com), because of this, changed language
settings in other components had no effect on subsequent visits to
tiqr.
Since tiqr no longer has a language switcher, there is no need to save
the locale. It now only reads the stepup_locale cookie and never
changes it.
See https://www.pivotaltracker.com/story/show/156334113
=> Don't store the locale in a cookie

src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Controller/ExceptionController.php
When a user has a permentent block, visiting /authentication triggered
a fatal error (class AppBundle not found) and there was a typo in the
error page title (.description.title -> .title).
=> Fix error in handling permanently blocked users

src/AppBundle/Resources/views/default/registration.html.twig
PR #40 broke registration if the initial page was loaded before
enrollment is initialized. The actual problem is the tiqr library not
distinguishing between 'session expired' and 'session not yet
started'. To work around this issue, we only interpret the idle status
as 'session expired' when we have seen a status other than idle.
=> Fix broken registration when enrollment not initialized

src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/translations/messages.nl.yml, src/AppBundle/Resources/views/default/authentication.html.twig
The page was too heigh for embedding in Office365. Solved by simply
adding less content to the page when the QR is opened.
The height is now 40 pixels less than before this change!
See https://www.pivotaltracker.com/story/show/156334113/comments/190026529
=> Use less content in authentication QR screen

app/config/config_test.yml, app/config/parameters.yml.dist, src/AppBundle/Controller/TiqrAppApiController.php, src/AppBundle/Features/Context/TiqrContext.php, src/AppBundle/Features/tiqrRegistration.feature, src/AppBundle/Resources/config/services.yml, src/AppBundle/Service/UserAgentMatcher.php, src/AppBundle/Service/UserAgentMatcherInterface.php
A new paramters.yml setting `mobile_app_user_agent_pattern` is checked
against the user agent received from the mobile app during
registration. If the pattern does not match, an error response is
returned. The default pattern allows any user agent string.
See [pivotal](https://www.pivotaltracker.com/story/show/133169279).
=> Check the user agent of mobile app against configurable pattern

src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Controller/CancelController.php, src/AppBundle/Controller/InfoController.php, src/AppBundle/Controller/RegistrationController.php, src/DevTiqrClientBundle/Controller/QrLinkController.php, src/SpBundle/Controller/SPController.php
All controller actions now have explicit rules as to how they can be
used. This was one of the points of feedback from the security audit.
The actions have been configured as can be seen in the `debug:router` output:
```
------------------------------------------ ---------- -------- ------ ----------------------------------- 
Name                                       Method     Scheme   Host   Path                               
------------------------------------------ ---------- -------- ------ ----------------------------------- 
_wdt                                       ANY        ANY      ANY    /_wdt/{token}                      
_profiler_home                             ANY        ANY      ANY    /_profiler/                        
_profiler_search                           ANY …
```
=> Specify allowed request methods on controller actions

composer.json, composer.lock
The changes in the GSSP bundle address some of the feedback from the security audit. More information about these changes can be found in Pivotal. ( https://www.pivotaltracker.com/story/show/158356753 and https://www.pivotaltracker.com/story/show/158356792)
=> Upgrade stepup-gssp-bundle to 2.1.0

app/AppKernel.php, app/config/routing.yml, app/config/security.yml, composer.json, composer.lock
The bundle was added as a composer dependency, installed in the project
and configured to serve health and info information on the /health and
/info endpoints.
See https://www.pivotaltracker.com/story/show/156880260
=> Install the monitor bundle

app/config/config.yml
Setting this to `session.handler.native_file` by default will fail on systems that have set something other than 'files' as `session.save_handler` in php.ini. Using the system default should always work.
This is in line with the other OC/stepup components
=> Use system session-handler by default

composer.lock, src/AppBundle/Features/Context/TiqrContext.php, yarn.lock
Notable upgrades:
- Tiqr server libphp was upgraded to 1.1.6 (thanks JoDi)
- Symfony upgraded to latest (3.4.15)
- SAML2 library to v3.2
See: Pivotal #158356708
=> Update composer and npm dependencies

src/AppBundle/Controller/AuthenticationController.php
The status of the Tiqr authentication was not returned after it
was successful because it would return an expired status as the
check depended on a Memcache value which was cleared after success so
the status returned an expired state. The logic order was changed so
first, we check for successful authentication and after that we check
if it's expired.
=> Fix tiqr authentication status

src/SpBundle/Controller/SPController.php
By disabling the entity loader, we prevent possible XXE exploitations. After disabling the loader, the previous state is reset.
=> Prevent XXE in SPController

app/config/parameters.yml.dist, composer.json, composer.lock, src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/DependencyInjection/Configuration.php, src/AppBundle/Resources/config/services.yml, src/AppBundle/Tiqr/TiqrConfiguration.php
Tiqr needs a fallback mechanism to support firebase as fallback
notification mechanism in case GCM fails. This issue was addressed
in the tiqr-server-libphp library but we also needed changes in Tiqr
itself to support the new configuration option.
=> Update tiqr-server-libphp to support firebase fallback

app/config/config.yml, webpack.config.js
Implement asset versioning as described in the Symfony docs: https://symfony.com/doc/current/frontend/encore/versioning.html. This solution differs from the way other StepUp apps apply asset versioning. This because these apps use Assetic (which is discouraged since Symfony embraced Encore). 
Also see Pivotal
https://www.pivotaltracker.com/story/show/164631198
=> Enable asset versioning using Encore

src/AppBundle/Resources/views/default/authentication.html.twig, src/AppBundle/Resources/views/default/registration.html.twig, src/SpBundle/Resources/views/default/sp.html.twig
To ensure good browser compatibility, any JS that is not transpiled by Babel, should be checked and fixed. We should not use any ES6 or newer language constructions.
For more details see the individual commit messages and the Pivotal ticket.
https://www.pivotaltracker.com/story/show/164629776
=> Remove modern js from twig templates

composer.lock
The recent tiqr/tiqr-server-libphp v1.1.10 upgrade brought us the support for android Firebase push notifications. The v1.1.11 release fixes a minor, very cosmetic issue where the Firebase push message text contained a redundant text.
=> Upgrade tiqr-server-libphp to v1.1.11

src/AppBundle/Resources/javascript/authentication.ts, src/AppBundle/Resources/views/default/authentication.html.twig, src/AppBundle/Resources/views/default/registration.html.twig, tsconfig.json, webpack.config.js
When TS was introduced TS was compiled to ECMASCRIPT 5. In older
browsers this seems a problem. Therefore now we compile TS to
ECMASCRIPT 3 to keep older browsers supported.
=> Add ECMAScript 3 support

CHANGELOG.md, app/config/parameters.yml.dist, src/AppBundle/Controller/AuthenticationController.php, src/AppBundle/Resources/config/services.yml
This should fix the deprecated GCM method. The api is returning a
`Error=DeprecatedEndpoint` error which prevents GCM users from
logging in.
=> Use FCM always as fallback for GCM

.travis.yml, README.md, app/Resources/scss/application.scss, composer.json, composer.lock, jest.config.js, package.json, src/AppBundle/Resources/javascript/StatusPollService.ts, src/DevTiqrClientBundle/Command/AuthenticationCommand.php, src/DevTiqrClientBundle/Command/RegistrationCommand.php, tsconfig.json, webpack.config.js, yarn.lock
The current travis build did not work since yarn tests/checks are not
running. This updates the js/css depencencies and restores the travis
build.
=> Restore js (security) tests

public/typescript/AuthenticationPageService.ts
In some rare conditions (chrome browser, only tiqr-token, coming from portal.office.com, etc) `document.location.replace(document.location.href);` does not seem to work. Using `location.reload();` seems to fix this.
_SURF issue CXT-50235_
=> Use location.reload() to prevent rare chrome issue

src/Controller/ExceptionController.php
When a unrecoverable error is thrown without a previous exception the
exception controller which displays the error message fails with an
fatal error. This is due to the display handler expecting a previous
exception which is not always the case.
The fatal error is resolved by extending the if condition and checking
for existence of the previous error.
See: https://www.pivotaltracker.com/n/projects/1163646/stories/177016742
=> Fix a fatal error in the exception controller

templates/default/authentication.html.twig, templates/default/registration.html.twig
Due to an issue in the twig template the javascript block was rendered
twice which could lead in a authentication error.
This moves the javascript block outside the body block which is also the
case in the parent template.
See: https://www.pivotaltracker.com/n/projects/1163646/stories/177016742
=> Resolve authentication issues due to duplicate notification call

src/Controller/AuthenticationController.php
The old school Symfony 3 forward was replaced with the modern FQN
counterpart.
=> Repair the Exception show forward

public/typescript/__test__/AuthenticationPageService.test.ts, public/typescript/__test__/RegistrationPageService.test.ts
This prevents the read only issues when dealing with overwriting the
location.  And makes the test Jest 27 proof.
https://www.pivotaltracker.com/story/show/180409642
=> Mock the window.location object

composer.json, composer.lock, src/Exception/TiqrServerRuntimeException.php, src/Features/registration.feature, src/Tiqr/Legacy/TiqrService.php, src/Tiqr/Legacy/TiqrUser.php, src/Tiqr/Legacy/TiqrUserRepository.php
The read write exceptions are catched in the code calling the library. The exceptions are explicitly translated to an exception of our own making. Mainly for decoupling reasons.
The application does not pay further attention to these situations. As in, it will produce a 500 error when any of these situations arise. No custom user facing error reports have been prioritized for now.
See: https://www.pivotaltracker.com/story/show/181553909
The biggest win for now is that the application does not continue execution after a critical point failed previously.
=> Catch the tiqr-server-libphp ReadWriteExceptions

.gitignore, CHANGELOG.md, composer.json, composer.lock, config/packages/dev/framework.yaml, config/packages/dev/monolog.yaml, src/DependencyInjection/Configuration.php, src/Features/authentication.feature, src/Features/registration.feature, src/Tiqr/Legacy/TiqrService.php, src/Tiqr/Legacy/TiqrUser.php, src/Tiqr/Legacy/TiqrUserRepository.php, src/Tiqr/TiqrFactory.php, yarn.lock
This serves as the intermediate branch between develop and tiqr library server upgrade work.
In this branch 2 features have already been accounted for
1. Logging was tweaked slightly for development environments. No deprecation warnings for now, they can be re-enabled at a later stage.
2. The high level integration has been performed. That is: all interface changes for the services have been applied. And high level tests for the file/memcache storage options have been done in my dev-vm. Where I noticed that device storage on filesystem did not work (probably a write issue to the /tmp folder) This storage engine does not allow us to set a custom save path :shrug: 
Please do a composer install to get the latest and greatest (dev) tiqr-server-libphp version into the tiqr gssp
=> Tiqr server library upgrade

src/Controller/TiqrAppApiController.php
An invalid secret should never happen during a normal use-case, so this should be logged as an error.
I could live with `warning` as well, but `info` just doesn't fit here.
=> Raise log level for invalid secret

composer.json
Run scripts on composer install/update, just like all the other modules in the stepup-suite.
=> Run cache:clear on composer install

translations/error/messages.en.yml, translations/error/messages.nl.yml
Fixes:
Since this error is triggered by the stepup-bundle, I wonder if this translation has to be added to other gssf's as well? I noticed webauthn doesn't have this tag as well..
=> Fix missing translation

assets/scss/application.scss, templates/default/authentication.html.twig
The form was not using the correct bootstrap form classes so was ugly
Before:
After:
=> Fix OTP form rendering classes

ci/qa/phpstan-baseline.neon, config/openconext/parameters.yaml.dist, src/Tiqr/TiqrConfiguration.php
The values from the config weren't set in the options. So this value was not used.
This should solve https://www.pivotaltracker.com/n/projects/1163646/stories/187786268
=> Add tokenCacheDir to the firebase options

dev/Command/AuthenticationCommand.php, src/Controller/AuthenticationController.php, src/Controller/TiqrAppApiController.php, src/Features/Context/TiqrContext.php, src/Features/tiqrAuthentication.feature, src/Features/tiqrRegistration.feature, src/Tiqr/Legacy/TiqrUser.php
Normally a client sends the notificationAddress and notificationType parameters with each registration and authentication response as HTTP POST parameters. In some situations however a tiqr client can not get a notification address. Different clients respond (and have responded) differently to this situation. The notificationAddress and notificationType parameters may be absent, or both or only notificationAddress maybe set to the string "(null)" or "NULL". This leads to several issues that this PR addresses:
* Currently there are user entries in the user storage table that have notificationAddress set to '(null)' or 'NULL'. Stepup-tiqr tries to send a push notification to these addresses, and that leads to an error. We change this behaviour so that NULL or (null) means no push address / …
=> Allow no notification address or type

ci/qa/phpstan-baseline.neon, ci/qa/phpstan.neon, dev/Command/AuthenticationCommand.php, dev/Command/RegistrationCommand.php, dev/FileLogger.php, dev/Twig/GsspExtension.php
The Authentication command wasn't able to read the QR code as text because it would try to convert to a string twice.
Also added PHPStan for all dev code and improved some other reported problems, improving code quality.
=> Fixed reading the QR code as text in the AuthenticationCommand on dev environments

assets/typescript/Component/RegistrationStatusComponent.ts, assets/typescript/RegistrationStateMachine.ts, assets/typescript/__test__/RegistrationPageService.test.ts, src/Controller/AuthenticationStatusController.php, src/Controller/RegistrationController.php, src/Service/TimeoutHelper.php, src/Tiqr/Legacy/TiqrService.php, src/Tiqr/TiqrServiceInterface.php, templates/default/registration.html.twig, tests/Unit/TimeoutHelperTest.php, translations/messages.en.yml, translations/messages.nl.yml
While polling for authn/registration state changes. The globally defined timeout periods for these actions where not tested explicitly. This PR ensures we start testing if the timeout period is expired. 
For registration, I added a new timeout error page. For this a new translation was added @pmeulen do you agree with my proposed translations? If not feel free to suggest better ones. I based these off the authn ones.
An offset time is substracted from the hard timeout time. This makes the timeout occur a couple of seconds before the actual timeout would take place. This prevents user actions taking place right before expiration time from erroring. 
See: https://www.pivotaltracker.com/story/show/188205272 (note that the story mentions registration/authentication sessions. These are not to …
=> Improve timeouts during registration/authentication polling

assets/typescript/Client/StatusClient.ts, assets/typescript/authentication.ts, assets/typescript/registration.ts, src/Controller/AuthenticationController.php, src/Controller/RegistrationController.php, src/EventSubscriber/RequiresActiveSessionAttributeListener.php, src/EventSubscriber/SessionStateListener.php, src/Service/SessionCorrelationIdService.php, src/Tiqr/Legacy/TiqrService.php, templates/default/authentication.html.twig, templates/default/registration.html.twig, tests/Unit/EventSubscriber/RequiresActiveSessionAttributeListenerTest.php, tests/Unit/EventSubscriber/SessionStateListenerTest.php, tests/Unit/Service/SessionCorrelationIdServiceTest.php, tests/Unit/Session/LoggingSessionFactoryTest.php
The polling async requests should include the correlation id based on the session id of the user that is placing them.
That way we can correlate between the access  logs and the application logs.
=> Add the session id derived id to polling requests

dependabot.yml, dev/Command/AuthenticationCommand.php
Prior to this change, dependabot would create pr's to upgrade from Symfony 6.4 to Symfony 7.1. We don't want this, because 7.1 will be eol in a couple of months, which can the increase maintenance burden. We will upgrade to 7.4 lts once it is released.
=> Tweak dependabot & fix dev bug

src/Tiqr/TiqrConfiguration.php
The Assert statements would yield unusable error messages without a path to know what to go and fix. This change at least tells us what config item is not right. And what is expected.
=> 1. Make the Tiqr Configuration validation less cryptic

config/openconext/parameters.yaml.dist, config/packages/framework.yaml, config/services.yaml, src/Attribute/RequiresActiveSession.php, src/Controller/AuthenticationNotificationController.php, src/Controller/AuthenticationQrController.php, src/Controller/AuthenticationStatusController.php, src/Controller/RegistrationController.php, src/EventSubscriber/RequiresActiveSessionAttributeListener.php, src/EventSubscriber/SessionStateListener.php, src/Service/SessionCorrelationIdService.php, src/Session/LoggingSessionFactory.php, src/Tiqr/Legacy/TiqrService.php, tests/Unit/EventSubscriber/RequiresActiveSessionAttributeListenerTest.php, tests/Unit/EventSubscriber/SessionStateListenerTest.php, tests/Unit/Service/SessionCorrelationIdServiceTest.php, tests/Unit/Session/LoggingSessionFactoryTest.php
Prior to this change there we weren't able to keep track of sessions that got lost.
This change allows us to see every time a session is created and distinguish them by their correlation id.
Log an error on a route that requires an active session when there is none
Prior to this change all routes were able to called, even though the user might not have had an active session
This change will start logging errors when the session wasn't found, or is in an unexpected state
Prior to this change session information got lost. We had no way of tracking down what happened to user sessions in the logs.
This change logs whether a session existed and if it's in a valid state. Log information is enriched with a correlation id to be able to distinguish them.
See …
=> 4. Improve logging on session related errors

assets/typescript/Client/StatusClient.ts, assets/typescript/authentication.ts, assets/typescript/registration.ts, composer.json, composer.lock, src/Controller/AuthenticationController.php, src/Controller/RegistrationController.php, templates/default/authentication.html.twig, templates/default/registration.html.twig, tests/Unit/EventSubscriber/RequiresActiveSessionAttributeListenerTest.php, tests/Unit/EventSubscriber/SessionStateListenerTest.php
Prior to this change, when a polling action from the browser hit the
server, and the server returned a 500, or some other error, it was not
possible to trace which session the browser belonged to.
This change adds a correlation id to the polling mechanism, so that id
can be used to search te logs for the origin of the session.
This should help retrace errors.
See: https://www.pivotaltracker.com/story/show/188205232
=> 5. Add the session id derived id to polling requests

config/services_test.yaml, src/Controller/AuthenticationController.php, src/Controller/RegistrationController.php, src/Controller/TiqrAppApiController.php, src/Features/Context/TiqrContext.php, src/Features/Context/WebContext.php, src/Features/authentication.feature, src/Features/mfaFatigueMitigation.feature, src/Features/registration.feature, src/Service/TrustedDeviceHelper.php
Prior to this change, the trusted device cookie was applied to the response to the tiqr app. Which was unintended, so the user would always be presented with a qr challenge.
This change puts the cookie on the authentication / registration request to the browser just before it is redirected back.
Fixes https://github.com/OpenConext/Stepup-tiqr/issues/341
=> Fix: Actually apply the trusted device cookie to the browser

config/openconext/parameters.yaml.dist, config/services.yaml, src/Controller/AuthenticationNotificationController.php, src/Service/TrustedDeviceHelper.php, tests/Unit/Controller/AuthenticationNotificationControllerTest.php
Prior to this change, it was not possible to do a 'warm' rollout of the notification fatique attack prevention feature.
This change makes this possible by disabling the enforcement of the check.
Fixes https://github.com/OpenConext/Stepup-tiqr/issues/343
=> Feature: Make trusted device cookie toggleable

assets/scss/application.scss, assets/typescript/Component/MobileOnlyComponent.ts, assets/typescript/authentication.ts, assets/typescript/registration.ts, templates/default/authentication.html.twig, templates/default/registration.html.twig, translations/messages.en.yml, translations/messages.nl.yml
Prior to this change, it was not clear users could tap the qr code on mobile. This change adds a button to touch-enabled browsers to ensure an optimal UX.
Fixes https://github.com/OpenConext/Stepup-tiqr/issues/342
=> Add 'Open in app' button below QR code
